/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import main.Book;
import main.FileManager;
import static main.FileManager.fileWriter;
import main.Library;
import static main.Library.inventory;

/**
 *
 * @author Joan Ye
 */
public class Delete extends javax.swing.JFrame {

    /**
     * Creates new form Delete
     */
    public Delete() {
        super("Delete student");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        jTxtareaDeleteList.setEditable(false);
        String list = "";
        try {
            list = FileManager.fileReader();
        } catch (IOException ex) {
            System.err.println("Error while reading the file.");
        } catch (NullPointerException ex) {
            System.out.println("- The file doesn't have data -");
        }
        jTxtareaDeleteList.setText(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblDelete = new javax.swing.JLabel();
        jBtnReturn = new javax.swing.JButton();
        jTxtISBN = new javax.swing.JTextField();
        jLblISBN = new javax.swing.JLabel();
        jBtnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtareaDeleteList = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));

        jLblDelete.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLblDelete.setText("DELETE BOOK");

        jBtnReturn.setBackground(new java.awt.Color(40, 40, 40));
        jBtnReturn.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBtnReturn.setForeground(new java.awt.Color(255, 255, 255));
        jBtnReturn.setText("Return");
        jBtnReturn.setFocusPainted(false);
        jBtnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReturnActionPerformed(evt);
            }
        });

        jLblISBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLblISBN.setText("ISBN");

        jBtnSubmit.setBackground(new java.awt.Color(0, 153, 255));
        jBtnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSubmit.setText("Submit");
        jBtnSubmit.setFocusPainted(false);
        jBtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubmitActionPerformed(evt);
            }
        });

        jTxtareaDeleteList.setColumns(20);
        jTxtareaDeleteList.setRows(5);
        jScrollPane1.setViewportView(jTxtareaDeleteList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLblISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnSubmit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnReturn)
                        .addGap(18, 18, 18)
                        .addComponent(jLblDelete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jBtnReturn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblISBN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSubmit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReturnActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnReturnActionPerformed

    private void jBtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubmitActionPerformed
        if (!jTxtISBN.getText().equals("")){
            Iterator it = inventory.keySet().iterator();
            //Variables
            String key = "";
            boolean found = false;
            Book deleteBook = new Book(jTxtISBN.getText());
            Book inventoryBook;
            // Verify if the book exists
            while (it.hasNext()) {
                key = (String) it.next();
                inventoryBook = inventory.get(key);
                if (inventoryBook.hashCode() == deleteBook.hashCode()) {
                    found = true;
                    break;
                }
            }
            // Delete the book if it is found
            if (found) {
                inventory.remove(key);
                // Save the changes in the file
                Menu menu = new Menu();
                try {
                    fileWriter();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Error while deleting the book.", "WARNING", JOptionPane.WARNING_MESSAGE);
                    menu.setVisible(true);
                    this.setVisible(false);
                }
                JOptionPane.showMessageDialog(this, "The book has deleted.", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
                menu.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "This book doesn't exist.", "WARNING", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Enter a title.", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnReturn;
    private javax.swing.JButton jBtnSubmit;
    private javax.swing.JLabel jLblDelete;
    private javax.swing.JLabel jLblISBN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtISBN;
    private javax.swing.JTextArea jTxtareaDeleteList;
    // End of variables declaration//GEN-END:variables
}
